"""embedding dimension 768 -> 1024 (BGE-M3)

Revision ID: 0016
Revises: 0015
Create Date: 2026-06-08 16:30:00

Switches the matching/knowledge embeddings from 768-dim (ko-sroberta) to
1024-dim (BAAI/bge-m3, multilingual SOTA). Embeddings are regenerated by the
embedding provider, so existing vectors are reset to NULL on dimension change.

Affected columns:
  - posts.content_emb
  - personas.context_emb
  - knowledge_units.embedding

ivfflat cosine indexes on posts/personas are dropped before the column change
and recreated afterwards. EMBED_DIM (src/buddle/ai/embeddings/base.py) is the
single source of truth and is set to 1024 to match this migration.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector

revision: str = "0016"
down_revision: str | None = "0015"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_OLD_DIM = 768
_NEW_DIM = 1024


def _recreate_indexes() -> None:
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_posts_content_emb "
        "ON posts USING ivfflat (content_emb vector_cosine_ops) WITH (lists = 100)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_personas_context_emb "
        "ON personas USING ivfflat (context_emb vector_cosine_ops) WITH (lists = 100)"
    )


def _resize(dim: int) -> None:
    # Drop ANN indexes that depend on the vector columns.
    op.execute("DROP INDEX IF EXISTS idx_posts_content_emb")
    op.execute("DROP INDEX IF EXISTS idx_personas_context_emb")

    # Dimension change is not castable in place; embeddings are regenerable,
    # so drop and re-add the columns as nullable vectors of the new dimension.
    op.drop_column("posts", "content_emb")
    op.add_column("posts", sa.Column("content_emb", Vector(dim), nullable=True))

    op.drop_column("personas", "context_emb")
    op.add_column("personas", sa.Column("context_emb", Vector(dim), nullable=True))

    op.drop_column("knowledge_units", "embedding")
    op.add_column("knowledge_units", sa.Column("embedding", Vector(dim), nullable=True))

    _recreate_indexes()


def upgrade() -> None:
    _resize(_NEW_DIM)


def downgrade() -> None:
    _resize(_OLD_DIM)
